import { db } from '../src/lib/db';

const FINTECH_STOCKS = [
  {
    ticker: "SQ",
    name: "Block, Inc.",
    sector: "Payments",
    subSector: "Point-of-Sale & Digital Payments",
    marketCap: "$28.5B",
    price: "$44.80",
    description: "Block (formerly Square) operates Cash App and Square POS ecosystem. Cash App has 57M+ monthly active users with growing Bitcoin and banking services. Square serves millions of SMBs with integrated hardware and software solutions.",
    website: "https://block.xyz",
    revenueGrowth: 62,
    marketOpportunity: 78,
    competitiveMoat: 68,
    profitabilityPath: 72,
    valuation: 70,
    industryKnowledge: 75,
    fiveXScore: 70,
  },
  {
    ticker: "UPST",
    name: "Upstart Holdings, Inc.",
    sector: "Lending",
    subSector: "AI-Powered Lending",
    marketCap: "$5.2B",
    price: "$58.30",
    description: "Upstart uses AI/ML to improve credit decisions, claiming 75% more approvals at same default rates. Expanded into auto loans and HELOC. Platform processes $1.5B+ in loans quarterly with growing bank partnerships.",
    website: "https://www.upstart.com",
    revenueGrowth: 75,
    marketOpportunity: 82,
    competitiveMoat: 60,
    profitabilityPath: 55,
    valuation: 65,
    industryKnowledge: 80,
    fiveXScore: 70,
  },
  {
    ticker: "NU",
    name: "Nu Holdings Ltd.",
    sector: "Digital Banking",
    subSector: "Latin America Neobank",
    marketCap: "$62.8B",
    price: "$12.15",
    description: "Nubank is the world's largest digital bank with 100M+ customers across Brazil, Mexico, and Colombia. Achieved profitability in 2023. Growing deposit base and expanding credit products in underpenetrated LatAm markets.",
    website: "https://www.nu.com.br",
    revenueGrowth: 85,
    marketOpportunity: 88,
    competitiveMoat: 75,
    profitabilityPath: 82,
    valuation: 60,
    industryKnowledge: 85,
    fiveXScore: 79,
  },
  {
    ticker: "SOFI",
    name: "SoFi Technologies, Inc.",
    sector: "Digital Banking",
    subSector: "Personal Finance & Lending",
    marketCap: "$14.8B",
    price: "$14.30",
    description: "SoFi offers a one-stop financial services platform with 10M+ members. Bank charter enables lower funding costs. Growing deposit base and expanding product suite from student loan refinancing to full banking services.",
    website: "https://www.sofi.com",
    revenueGrowth: 68,
    marketOpportunity: 72,
    competitiveMoat: 58,
    profitabilityPath: 70,
    valuation: 62,
    industryKnowledge: 72,
    fiveXScore: 67,
  },
  {
    ticker: "LMND",
    name: "Lemonade, Inc.",
    sector: "Insurtech",
    subSector: "AI-Powered Insurance",
    marketCap: "$1.1B",
    price: "$14.20",
    description: "Lemonade uses AI for instant insurance quotes and claims processing. Expanded from renters to homeowners, pet, life, and car insurance. Growing premium in-force with improving loss ratios and European expansion underway.",
    website: "https://www.lemonade.com",
    revenueGrowth: 55,
    marketOpportunity: 70,
    competitiveMoat: 45,
    profitabilityPath: 35,
    valuation: 80,
    industryKnowledge: 65,
    fiveXScore: 58,
  },
  {
    ticker: "AFRM",
    name: "Affirm Holdings, Inc.",
    sector: "Lending",
    subSector: "Buy Now Pay Later",
    marketCap: "$16.2B",
    price: "$54.70",
    description: "Affirm is a leading BNPL platform with transparent, no-late-fee lending. Partners with Amazon, Shopify, Walmart. Growing merchant network and expanding debit+ card offering. Approaching GAAP profitability.",
    website: "https://www.affirm.com",
    revenueGrowth: 70,
    marketOpportunity: 68,
    competitiveMoat: 55,
    profitabilityPath: 65,
    valuation: 55,
    industryKnowledge: 68,
    fiveXScore: 64,
  },
  {
    ticker: "ADYEY",
    name: "Adyen N.V.",
    sector: "Payments",
    subSector: "Global Payment Processing",
    marketCap: "$52.3B",
    price: "$1,620.00",
    description: "Adyen provides a single global platform for accepting payments worldwide. Serves enterprise clients like Meta, Uber, Spotify. Known for superior technology, high margins (65%+ take-rate margin), and disciplined growth.",
    website: "https://www.adyen.com",
    revenueGrowth: 58,
    marketOpportunity: 85,
    competitiveMoat: 82,
    profitabilityPath: 90,
    valuation: 45,
    industryKnowledge: 78,
    fiveXScore: 72,
  },
  {
    ticker: "SHOP",
    name: "Shopify Inc.",
    sector: "Commerce",
    subSector: "E-Commerce Platform & Payments",
    marketCap: "$98.5B",
    price: "$76.50",
    description: "Shopify powers millions of merchants globally with commerce infrastructure. Shopify Payments, Capital, and Logistics create an ecosystem lock-in. Growing off-OMS penetration and B2B wholesale features drive expansion.",
    website: "https://www.shopify.com",
    revenueGrowth: 60,
    marketOpportunity: 80,
    competitiveMoat: 78,
    profitabilityPath: 85,
    valuation: 40,
    industryKnowledge: 72,
    fiveXScore: 69,
  },
  {
    ticker: "COIN",
    name: "Coinbase Global, Inc.",
    sector: "Crypto",
    subSector: "Cryptocurrency Exchange",
    marketCap: "$42.5B",
    price: "$172.40",
    description: "Coinbase is the largest US crypto exchange with 110M+ verified users. Base L2 network growing rapidly. Institutional custody business and staking revenue provide diversification beyond trading fees.",
    website: "https://www.coinbase.com",
    revenueGrowth: 72,
    marketOpportunity: 75,
    competitiveMoat: 60,
    profitabilityPath: 55,
    valuation: 48,
    industryKnowledge: 70,
    fiveXScore: 64,
  },
  {
    ticker: "HOOD",
    name: "Robinhood Markets, Inc.",
    sector: "Trading",
    subSector: "Retail Trading Platform",
    marketCap: "$18.2B",
    price: "$20.80",
    description: "Robinhood pioneered commission-free trading with 23M+ funded accounts. Expanding into retirement accounts, credit cards, and futures. Gold subscription growing. Crypto and options revenue diversifying income.",
    website: "https://robinhood.com",
    revenueGrowth: 65,
    marketOpportunity: 62,
    competitiveMoat: 50,
    profitabilityPath: 68,
    valuation: 58,
    industryKnowledge: 65,
    fiveXScore: 61,
  },
  {
    ticker: "MQ",
    name: "Marqeta, Inc.",
    sector: "Payments",
    subSector: "Card Issuing Platform",
    marketCap: "$3.8B",
    price: "$5.90",
    description: "Marqeta provides modern card issuing infrastructure powering Block's Cash App, Uber, and Instacart. Open API platform enables just-in-time funding and dynamic spend controls. Expanding into credit and international markets.",
    website: "https://www.marqeta.com",
    revenueGrowth: 50,
    marketOpportunity: 72,
    competitiveMoat: 62,
    profitabilityPath: 48,
    valuation: 75,
    industryKnowledge: 68,
    fiveXScore: 63,
  },
  {
    ticker: "MELI",
    name: "MercadoLibre, Inc.",
    sector: "Commerce & Fintech",
    subSector: "LatAm E-Commerce & Digital Payments",
    marketCap: "$102.5B",
    price: "$2,045.00",
    description: "MercadoLibre dominates Latin American e-commerce and fintech. Mercado Pago processes $140B+ annually with 50M+ active users. Credit business growing 80%+ YoY. Combines Amazon + PayPal for LatAm.",
    website: "https://www.mercadolibre.com",
    revenueGrowth: 78,
    marketOpportunity: 90,
    competitiveMoat: 85,
    profitabilityPath: 88,
    valuation: 35,
    industryKnowledge: 82,
    fiveXScore: 76,
  },
  {
    ticker: "WISE",
    name: "Wise plc",
    sector: "Payments",
    subSector: "Cross-Border Money Transfer",
    marketCap: "$12.8B",
    price: "$13.15",
    description: "Wise provides low-cost cross-border payments with 12M+ customers. Average cost 0.67% vs 6% industry average. Wise Platform embedded in banks globally. Growing business offering and interest income on customer balances.",
    website: "https://wise.com",
    revenueGrowth: 58,
    marketOpportunity: 75,
    competitiveMoat: 70,
    profitabilityPath: 80,
    valuation: 55,
    industryKnowledge: 72,
    fiveXScore: 68,
  },
  {
    ticker: "PLTR",
    name: "Palantir Technologies Inc.",
    sector: "Enterprise AI",
    subSector: "AI & Data Analytics for Finance",
    marketCap: "$180.2B",
    price: "$78.50",
    description: "Palantir provides AI-powered data analytics platforms used by major financial institutions. AIP (Artificial Intelligence Platform) driving commercial revenue growth 25%+ YoY. Foundry platform used for anti-fraud, risk, and compliance.",
    website: "https://www.palantir.com",
    revenueGrowth: 65,
    marketOpportunity: 82,
    competitiveMoat: 78,
    profitabilityPath: 85,
    valuation: 28,
    industryKnowledge: 70,
    fiveXScore: 67,
  },
  {
    ticker: "PATH",
    name: "UiPath Inc.",
    sector: "Automation",
    subSector: "RPA for Financial Services",
    marketCap: "$7.2B",
    price: "$12.80",
    description: "UiPath leads RPA market with deep penetration in financial services automation. AI-powered document understanding and process mining. Transitioning to cloud subscription model with 10K+ enterprise customers.",
    website: "https://www.uipath.com",
    revenueGrowth: 42,
    marketOpportunity: 65,
    competitiveMoat: 62,
    profitabilityPath: 60,
    valuation: 68,
    industryKnowledge: 58,
    fiveXScore: 59,
  },
  {
    ticker: "FLYT",
    name: "Flywire Corporation",
    sector: "Payments",
    subSector: "Vertical-Specific Payments",
    marketCap: "$2.1B",
    price: "$67.20",
    description: "Flywire specializes in complex, high-value vertical payment flows (education, healthcare, travel). Processing $30B+ annually. Proprietary receivables platform with strong network effects in niche verticals.",
    website: "https://www.flywire.com",
    revenueGrowth: 52,
    marketOpportunity: 60,
    competitiveMoat: 58,
    profitabilityPath: 62,
    valuation: 62,
    industryKnowledge: 55,
    fiveXScore: 58,
  },
];

async function seed() {
  console.log("🌱 Seeding database...");

  // Seed stocks
  for (const stock of FINTECH_STOCKS) {
    await db.stock.upsert({
      where: { ticker: stock.ticker },
      update: stock,
      create: stock,
    });
  }
  console.log(`✅ Seeded ${FINTECH_STOCKS.length} fintech stocks`);

  // Seed default factor weights
  const existingWeights = await db.factorWeight.findFirst();
  if (!existingWeights) {
    await db.factorWeight.create({
      data: {
        revenueGrowth: 0.20,
        marketOpportunity: 0.20,
        competitiveMoat: 0.20,
        profitabilityPath: 0.15,
        valuation: 0.15,
        industryKnowledge: 0.10,
      },
    });
    console.log("✅ Seeded default factor weights");
  }

  console.log("🎉 Seeding complete!");
}

seed()
  .catch((e) => {
    console.error("Seed error:", e);
    process.exit(1);
  })
  .finally(async () => {
    await db.$disconnect();
  });
