export interface Story {
  id: string;
  titleZh: string;
  titleEn: string;
  descriptionZh: string;
  descriptionEn: string;
  emoji: string;
  category: string;
  categoryZh: string;
  categoryEn: string;
  gradient: string;
  paragraphsZh: string[];
  paragraphsEn: string[];
}

export const CATEGORIES = [
  { id: 'all', zh: '全部', en: 'All' },
  { id: 'fantasy', zh: '奇幻冒险', en: 'Fantasy' },
  { id: 'superhero', zh: '超级英雄', en: 'Superheroes' },
  { id: 'mystery', zh: '神秘探索', en: 'Mystery' },
  { id: 'space', zh: '星际冒险', en: 'Space' },
  { id: 'magic', zh: '魔法世界', en: 'Magic' },
  { id: 'history', zh: '历史传说', en: 'History' },
  { id: 'digital', zh: '数字世界', en: 'Digital' },
  { id: 'ocean', zh: '深海奇旅', en: 'Ocean' },
];

export const stories: Story[] = [
  {
    id: 'ice-queen',
    titleZh: '冰雪女王的礼物',
    titleEn: "The Ice Queen's Gift",
    descriptionZh: '小公主艾雪拥有冰雪力量，却因害怕而屡屡失控。她能在大敌当前之际，用爱唤醒真正的魔法吗？',
    descriptionEn: 'Princess Elsa fears her own ice powers — until love shows her the true secret of her magic.',
    emoji: '❄️',
    category: 'fantasy',
    categoryZh: '奇幻冒险',
    categoryEn: 'Fantasy',
    gradient: 'from-blue-500 via-cyan-500 to-indigo-600',
    paragraphsZh: [
      '在遥远的北方，有一座被雪山环绕的王国，叫做冰晶城。城里住着一位五岁的小公主，名叫艾雪。她有银白色的头发，两只蓝宝石一样的眼睛，还有一个让她既骄傲又害怕的秘密——她的双手能够制造冰雪。',
      '三天前，艾雪一高兴就把花园的喷泉冻住了。昨晚，她做噩梦惊醒，把整个卧室都结成了冰窟。今天是她的生日，她偷偷向天空祈祷："求你了，千万别出乱子。"',
      '生日宴会上，宫殿里挤满了宾客，音乐声和笑声交织在一起。好朋友格鲁把一束五颜六色的气球塞进艾雪的手里："来，你来放气球！"艾雪太开心了，一阵激动涌上心头——冰雪之力突然失控！',
      '嗖的一声，一道寒气从她掌心喷射而出。所有气球瞬间冻成冰球，噼里啪啦地掉在地上。蛋糕结冰了，喷泉冻成了雕像，就连国王的胡须上也挂起了冰柱！宾客们惊叫着四散逃跑。',
      '"我是怪物！"艾雪哭着说，转身冲出宫殿，跑进了后山的雪林深处。她跑啊跑，跑到再也迈不动脚，倒在一棵巨大的冰晶树下。奇怪的是，她一点儿也不觉得冷。',
      '就在这时，一道低沉而温和的声音从树后传来："小公主，我在这里等你很久了。"艾雪吓了一跳，但不知为什么，那个声音让她感到一种莫名的安心。',
      '一条巨龙从冰晶树后缓缓走出来。它浑身覆盖着蓝白色的鳞片，每一片都像月光一样闪光。它的眼睛温柔而深邃，像两颗古老的蓝宝石。"不要怕，"它说，"我叫银霜。三百年前，北方精灵派我来守护你们的王国。"',
      '"守护我们？"艾雪擦了擦眼泪，"可是我只会破坏东西！"银霜摇摇头，"那是因为你在害怕。冰雪之力是情感的镜子——你越恐惧，它越失控；你越充满爱，它就越温柔，越强大。"',
      '"但是，"银霜继续说，它用尾巴在雪地上画出一幅地图，"你们王国正面临危险。一片黑影之咒从南方蔓延而来，它会让人们忘记所有美好的事物。能阻止它的，只有真正的冰雪之力，而那个人，就是你。"',
      '"是我？"艾雪望着自己的双手。"是的，"银霜说，"但你必须先学会控制力量。来，闭上眼睛，想一件让你最快乐的事，不用管力量，就只是回想那件事。"',
      '艾雪闭上眼睛。她想到了妈妈每晚给她讲故事的声音，想到了爸爸用胡须蹭她脸颊时她咯咯笑的样子，想到了哥哥阿诺总是在她背后悄悄保护她……嘴角慢慢弯起来。',
      '"睁开眼睛，"银霜轻声说。艾雪睁眼一看——她的手心上，开出了一朵完美的六瓣冰晶花，晶莹剔透，美丽极了。"这才是你真正的力量，"银霜点点头，"从今天起，我来教你。"',
      '接下来的六天，银霜教艾雪用情感驾驭冰雪。她学会了用思念家人来制造温柔的雪花，用对朋友的爱来建造坚固的冰盾。冰雪之力慢慢变得像她的手指一样听话。',
      '第七天清晨，山下传来急促的号角声。银霜神色凝重地说："黑影来了。"艾雪和银霜飞奔到城墙上，向南望去——一片浓稠的黑色阴影正从地平线上滚滚而来，所过之处颜色尽失。',
      '但艾雪发现，在黑影的边缘，有一个小小的身影正拼命向城墙跑来，挥舞着双手。那橙色的外套……那熟悉的跑步姿势……"哥哥！"艾雪尖叫起来。',
      '"黑影有一种力量，"银霜轻声说，"它让人们把所有靠近的东西都当作威胁。你的哥哥阿诺两年前出发寻找北方草药，从未放弃回家的念头。但黑影让所有人误以为他是敌人。只有心中充满爱的人，才能看穿那个谎言。"',
      '艾雪的眼泪夺眶而出。哥哥一直在找回家的路！她深吸一口气，闭上双眼，想起了哥哥给她擦眼泪的手，想起了他轻声唱给她的催眠曲……胸口涌出一股巨大的温暖。',
      '艾雪张开双臂。冰雪之力汹涌而出，但这一次，它不是在暴走，而是化作无数耀眼的冰晶星，如瀑布般倾泻向黑影。每一颗冰晶落下，黑影就退缩一分，哀嚎着收缩……直到——砰！黑影彻底散去！',
      '阳光重新照耀大地。城门缓缓打开，哥哥阿诺踉踉跄跄地跑进来，手里捧着一束银蓝色的花——那是只生长在极北之地的冰心花，传说能治愈一切心灵的创伤。"我去给你找礼物，"他气喘吁吁地说，"找了两年，才找到。"',
      '艾雪扑进哥哥怀里，哭了又笑。银霜在旁边轻声说："艾雪，你今天做到了最难的事——用爱战胜了恐惧。这就是冰雪之力真正的秘密。"从此，冰晶城无论什么季节，天空中都能看见美丽的蓝色雪晶飞舞，那是艾雪快乐的证明。',
    ],
    paragraphsEn: [
      'Far in the north, surrounded by snow-capped mountains, lay the Kingdom of Frost Crystal. Five-year-old Princess Elsa had silver hair, eyes the color of sapphires, and a secret that both thrilled and terrified her — her hands could create ice and snow.',
      'Three days ago, she had accidentally frozen the garden fountain when she felt excited. Last night, a nightmare woke her and turned her whole bedroom into an ice cave. Today was her birthday, and she made one silent wish to the sky: "Please, please don\'t let anything go wrong."',
      'The birthday party filled the palace with music and laughter. Her best friend Gru pressed a bunch of colorful balloons into her hands. "Here, you release the balloons!" Too much joy flooded her heart — and her ice powers burst free without warning!',
      'A blast of cold shot from her palms. Every balloon froze solid and clattered to the floor like little ice balls. The cake iced over, the fountain became a statue, and the King\'s beard grew a row of icicles. Guests screamed and ran in all directions.',
      '"I\'m a monster!" Elsa sobbed, and she ran — out of the palace, into the snowy forest behind the mountains. She ran until her legs gave out and she collapsed under a giant crystal tree. Strangely, she didn\'t feel cold at all.',
      'Then a deep, gentle voice came from behind the tree: "Little princess, I have been waiting for you." Elsa startled, but the voice made her feel oddly at ease.',
      'A dragon stepped slowly from behind the tree. Its scales were blue-white, each one glowing like moonlight. Its eyes were warm and ancient, like two sapphires. "Don\'t be afraid," it said. "My name is Silver Frost. Three hundred years ago, the Northern Spirits sent me to guard your kingdom."',
      '"Guard us?" Elsa wiped her tears. "But I only destroy things!" Silver Frost shook its great head. "That\'s because you\'re afraid. Ice magic mirrors your feelings. The more you fear it, the more it rages. The more you love, the more gentle and powerful it becomes."',
      '"But your kingdom faces danger," Silver Frost continued, tracing a map in the snow with its tail. "A Shadow Curse is spreading from the south, draining all color and joy from the world. The only power that can stop it is true ice magic — and that power belongs to you."',
      '"Me?" Elsa stared at her hands. "Yes," said Silver Frost. "But first, you must learn to control it. Close your eyes. Think of the thing that makes you happiest. Don\'t worry about your power — just remember that feeling."',
      'Elsa closed her eyes. She thought of her mother\'s storytelling voice at bedtime, her father\'s scratchy beard tickling her cheek, and her brother Arno — who always walked one step behind her, quietly keeping her safe. A smile crept across her face.',
      '"Open your eyes," Silver Frost said softly. Elsa looked — and in her palm bloomed a perfect six-petaled snowflake, crystal clear and radiant. "That is your true power," Silver Frost said. "Now let me teach you."',
      'For six days Silver Frost guided her. She learned to channel her love for family into gentle snowflakes, and her love for friends into shields of solid ice. Day by day, her power grew as obedient as her own fingers.',
      'On the seventh morning, warning horns blared from the valley. "The Shadow is here," said Silver Frost grimly. They raced to the city walls. To the south, a thick black darkness rolled in, stripping all color from everything it touched.',
      'But at the shadow\'s edge, Elsa spotted a tiny figure running toward the gate, waving desperately. That orange coat. That familiar way of running. "Arno!" she screamed.',
      '"The Shadow has a power," Silver Frost said quietly. "It makes people fear every approaching thing. Your brother has been gone two years searching for healing herbs in the north — he never stopped trying to come home. But the Shadow made everyone believe he was the enemy. Only a heart full of love can see through that lie."',
      'Tears poured down Elsa\'s face. Arno had never abandoned her! She took a deep breath, closed her eyes, and thought of Arno drying her tears, singing her lullabies — and a tremendous warmth surged from her heart.',
      'Elsa spread her arms wide. Her power erupted — but this time, not in destruction. It transformed into thousands of shining ice crystals that cascaded like a waterfall onto the shadow. With every crystal that fell, the shadow shrank and wailed, smaller and smaller, until — boom — it was gone.',
      'Sunlight flooded the land. The gates opened. Arno stumbled in, his coat tattered, clutching a bouquet of silver-blue flowers — the legendary Ice Heart Flower, found only at the world\'s frozen edge, said to heal any wounded soul. "I went to get you a gift," he panted. "Took two years to find it."',
      'Elsa ran into his arms, laughing and crying at once. Silver Frost said quietly, "You did the hardest thing today, Elsa. You defeated fear with love. That is the true secret of your power." And from that day on, beautiful blue crystals could always be seen drifting through the skies of Frost Crystal Kingdom — proof that the princess was happy.',
    ],
  },

  {
    id: 'digital-world',
    titleZh: '数码世界大冒险',
    titleEn: 'Digital World Adventure',
    descriptionZh: '七岁的小美从平板电脑里孵化出一只数码宠物花花！她们必须一起穿越四个数字王国，拯救正在消失的数码世界。',
    descriptionEn: 'Maya hatches a digital creature called Blossom from her tablet — and together they must save a fading digital world.',
    emoji: '🌸',
    category: 'digital',
    categoryZh: '数字世界',
    categoryEn: 'Digital',
    gradient: 'from-green-500 via-teal-500 to-emerald-600',
    paragraphsZh: [
      '七岁的小美从来没想到，她的平板电脑里会住着一个秘密。那天晚上，屏幕突然闪起彩虹色的光，一颗蛋形图标开始疯狂闪烁。小美好奇地戳了一下——图标裂开了！',
      '一团光球从平板里飘出来，落在床上，慢慢变成了一只圆滚滚的小生物——大大的紫色眼睛，毛茸茸的身体，头顶长着一朵可爱的小花。"你好，"它奎声说，"我叫花花。我是你的数码宠物！"',
      '小美张大了嘴。"数码宠物？"她压低声音问。花花骄傲地挺起胸膛，"对！我来自数码世界，那是存在于网络里的神奇世界。但是出了大麻烦——有人偷走了数码世界的核心代码！没有它，我们的世界会一点一点消失。你看——"花花的身体已经半透明了。',
      '"核心代码被分成四块，藏在数码世界的四个地方，"花花说，"我需要你和我一起去找回来！你愿意去吗？"小美毫不犹豫地点了点头，"当然去！"',
      '花花碰了碰平板，屏幕再次闪起彩虹光。小美感觉自己被吸了进去——等她再睁开眼，她已经站在一片像素森林里。树叶是方块形的，小鸟是像素拼成的，就连天空都是一格一格的蓝色。',
      '"第一块代码在火焰山，"花花说，"由一条火龙守护着。它脾气很坏——但我觉得它只是太孤独了。"火焰山上，火龙喷着火焰，把所有靠近的人都吓跑。小美站在原地，鼓起勇气大声喊："我来帮你建一座瞭望台，让你站在最高处守护你的家！"',
      '火龙愣住了。从来没有人说过要帮助它。它慢慢低下头，把第一块代码交了出来，眼角还有一滴光晶般的眼泪。原来，它守护这里已经三百年了，从未有人说过谢谢。',
      '第二块代码在冰雪谷。冰雪精灵误以为小美是来抢夺她们宝石的，把她们团团包围。小美灵机一动，用手比划着画出了一幅图案——一座会让所有人都能欣赏宝石之美的博物馆。精灵们欢喜地扑上来，送出了代码。',
      '第三块代码在彩虹桥上。一个数据巨人守着桥，因为太孤独而变得暴躁。小美没有硬闯，而是坐在桥头，开始给巨人讲她在学校发生的有趣事情。巨人越听越入迷，最终哈哈大笑，把代码当作礼物送给了她。',
      '第四块代码在星光海。数据鱼们迷路了，找不到回家的路，在黑暗中乱窜。花花想起它在数码世界学过的一首古老歌谣，开始轻声哼唱。鱼儿们循着歌声汇聚起来，感激地将代码奉上。',
      '当小美拿到最后一块代码，花花突然消失了——变成一堆闪光的数据粒子飘散在空中！"花花！"小美惊叫，泪水涌上眼眶。一个微弱的声音从空气里传来："把……代码拼在一起……"',
      '小美颤抖着将四块代码合在一起。一道彩虹光爆发出来，整个数码世界剧烈震动！然后，平静了。空气中，一只比以前大得多的花花慢慢凝聚而出，翅膀上长满彩虹色的羽毛，眼神更加明亮，更加睿智。',
      '"你进化了！"小美激动地说。花花绕着她飞了三圈，"是的！数码宠物完成使命后就会进化。但我进化的原因，不是因为代码，而是因为有你陪着我——谢谢你，我的伙伴。"',
      '回到现实世界后，平板屏幕上多了一个新图标：一朵彩虹花，带着花花温柔的笑脸。从那以后，每当小美遇到困难，那朵花就会轻轻闪动，好像在说：别怕，你不是一个人。',
    ],
    paragraphsEn: [
      'Seven-year-old Maya never suspected her tablet was hiding a secret. One evening the screen blazed with rainbow light, and an egg-shaped icon began to flash wildly. Maya tapped it — and the egg cracked open!',
      'A ball of light floated out and slowly became a round, fluffy creature with large purple eyes and a tiny flower growing from its head. "Hello," it said in a small voice. "My name is Blossom. I\'m your Digimon!"',
      'Maya\'s mouth fell open. Blossom stood tall and explained: "I come from the Digital World — a magical world inside the internet. But something terrible has happened. Someone stole the Master Code! Without it, our world will disappear piece by piece." Blossom held up a tiny paw — already half transparent.',
      '"The Code was split into four pieces hidden in four digital zones," Blossom said. "I need you to come with me and get them back. Will you?" Maya nodded without hesitating. "Of course!"',
      'Blossom touched the tablet. Rainbows swirled. Maya felt herself pulled forward — and when she opened her eyes she was standing in a pixel-style forest. Block-shaped leaves, square birds, and a sky tiled in patches of blue.',
      '"The first piece is at Volcano Mountain, guarded by a fire dragon," Blossom said. "It has a temper — but I think it\'s just lonely." The dragon roared and belched flames at everyone who came near. Maya stood her ground and shouted up: "I want to help you build a watchtower — so you can stand at the very top and guard your home!"',
      'The dragon froze. Nobody had ever offered to help it before. Slowly it lowered its head and handed over the Code fragment, a single glittering tear rolling down its scales. It had guarded this volcano for three hundred years without a single thank-you.',
      'The second piece was in the Crystal Valley, where ice sprites thought Maya had come to steal their gems and surrounded her. Maya quickly drew a picture in the air with her finger — a museum where everyone could admire the gems\' beauty. The sprites squealed with delight and gave her the Code.',
      'The third piece was on the Rainbow Bridge, where a data giant had grown grumpy from loneliness. Maya didn\'t try to fight past it. She simply sat at the bridgehead and began telling the giant funny stories from school. The giant listened, then laughed so hard the bridge shook, and happily handed over the Code.',
      'The fourth piece was in the Star Sea, where a school of data-fish were lost in the dark, darting in every direction. Blossom remembered an old Digital World song and began to hum it softly. The fish gathered toward the melody, grateful, and offered up the final Code fragment.',
      'The moment Maya held all four pieces, Blossom vanished — dissolving into sparkling data-motes that floated away. "Blossom!" Maya cried. A fading voice drifted through the air: "Put... the pieces... together..."',
      'With trembling hands Maya joined the four fragments. A rainbow explosion filled the sky and the whole Digital World shuddered — then went quiet. Slowly, a Blossom far larger than before took shape, with brilliant rainbow-feathered wings and brighter, wiser eyes.',
      '"You evolved!" Maya exclaimed. Blossom circled her three times. "Yes! Digimon evolve after completing their mission. But I didn\'t evolve because of the Code. I evolved because you were with me. Thank you, partner."',
      'Back in the real world, Maya\'s tablet now showed a new icon: a rainbow flower with Blossom\'s gentle smile. Whenever Maya faced a hard day from then on, the little flower would glow softly — as if to say: don\'t worry. You\'re not alone.',
    ],
  },

  {
    id: 'strange-town',
    titleZh: '奇异镇的秘密',
    titleEn: 'The Secret of Strange Town',
    descriptionZh: '枫叶镇的路灯每晚午夜都在闪烁，而十岁的小卓发现，那些闪烁里藏着一条来自神秘精灵的求救信息……',
    descriptionEn: 'Maplewood\'s streetlights flicker every midnight — and Zoe discovers they\'re a distress signal from a trapped fairy.',
    emoji: '🔮',
    category: 'mystery',
    categoryZh: '神秘探索',
    categoryEn: 'Mystery',
    gradient: 'from-purple-500 via-violet-500 to-pink-600',
    paragraphsZh: [
      '枫叶镇的路灯有个怪毛病：每天夜里十二点，它们会按照某种规律忽明忽暗，不停地闪烁。大人们都说那只是电路老化，没什么大不了。但是十岁的小卓不这么认为——她觉得那些闪烁里藏着密码。',
      '小卓趴在卧室窗台上，拿着笔记本记录路灯的闪烁规律——长闪代表横线，短闪代表点。三天后，她破译了！那是摩尔斯电码，翻译过来是：帮帮我，我被困住了，第七号灯柱，根部。',
      '小卓叫上了好朋友小乐，两个人半夜偷偷溜出去，来到第七号灯柱前。灯柱根部有一道细小的缝隙，里面有橙色的光在闪动。"谁在那里？"小卓弯腰问。',
      '"我叫流萤，我是枫叶镇的电力精灵，"一个只有萤火虫大小的橙色光点从缝隙里飞出来，落在小卓手掌上，"三年前，镇上改造了电力系统，把我赖以生存的旧许愿井封死了。我被困在电网里出不来，只能靠控制路灯发出信号。"',
      '"许愿井？"小乐好奇地歪头。流萤点点头，"很久很久以前，许愿井是枫叶镇的心脏，连接着自然和人类的情感。有了它，镇里的花儿开得特别好，孩子们做的梦也特别甜。但井被封死之后……你们有没有发现，镇上的花越来越少了？"',
      '小卓想了想——还真是！奶奶家门前曾经有大片薰衣草，现在只剩几棵蔫蔫的。"那我们把井挖开不就行了？"小乐说。流萤摇头，"不行，自己挖开会破坏地下的能量平衡，必须先取出我留在井底的封印石，送到镇中心的老橡树下，才能安全开封。"',
      '"封印石在哪里？""就在井底，"流萤叹了口气，"好消息是，井口只剩一个拳头大的缝隙——只有孩子的小手才能伸进去。"小卓撸起袖子，带着小乐找到了那口废弃的旧许愿井。',
      '井口果然被水泥封了，只留着一道小缝。小卓把手伸进去，摸啊摸，摸到了一块温热的、刻着奇怪花纹的石头。"有了！"她小心翼翼地把石头取了出来。',
      '她们把封印石带到镇中心的老橡树下，把石头压进树根旁边的泥土里。等了好一会儿……什么都没发生。小卓开始担心起来。"还差一样东西，"流萤说，"许愿井需要一个真诚的愿望来激活。你们最真诚的愿望是什么？"',
      '小卓和小乐互相看了一眼。小卓认真地说："我希望枫叶镇的花重新盛开，我希望大家都开心。"小乐补充说："我希望奶奶的身体快点好，我希望镇上的孩子们都能做甜甜的梦。"',
      '橡树开始轻轻颤动。橙色的光从树根深处涌出，沿着地下脉络向四面八方扩散……整个枫叶镇的地下都悄悄亮了起来！',
      '流萤从小卓手心腾起，越变越大——从一粒光点变成了手掌大小的小精灵，长着橙色的翅膀和绿宝石般的眼睛，美极了。"谢谢你们！我终于自由了！"它高兴地飞旋着。',
      '第二天清晨，枫叶镇的人们推开窗户，惊讶得说不出话——镇上所有的花在一夜之间全部盛开了！薰衣草、玫瑰、向日葵……到处都是颜色和香味。奶奶门前重新变成了一片紫色的海洋。',
      '从此，小卓和小乐有了一个神秘的朋友。每天夜里，路灯依然在闪烁，但这次，灯光传递的只有两个字："谢谢。"',
    ],
    paragraphsEn: [
      'The streetlights of Maplewood Town had a strange habit: every night at midnight they flickered in patterns — long and short flashes, over and over. Adults said it was just aging wires. But ten-year-old Zoe was convinced the flickers were hiding a code.',
      'For three nights she sat at her window, recording every flash in her notebook. Long flash meant dash, short flash meant dot. On the third night she cracked it: Morse code that read — "Help me. I\'m trapped. Lamppost seven. At the roots."',
      'Zoe grabbed her best friend Leo, and the two of them slipped out at midnight. At the base of lamppost seven, a tiny crack glowed orange. "Who\'s there?" Zoe crouched down and whispered.',
      '"My name is Lumina. I\'m Maplewood\'s electricity fairy." A light-speck no bigger than a firefly floated out and landed on Zoe\'s palm. "Three years ago the town sealed the old Wishing Well to build a new power station. I\'ve been trapped in the electrical grid ever since. The only way I can send a message is through the streetlights."',
      '"The Wishing Well was the heart of this town," Lumina explained, "connecting nature and human feelings. Without it, the flowers stopped blooming and children\'s dreams turned gray. Haven\'t you noticed — Maplewood\'s gardens are nearly bare?"',
      'Zoe thought about it. Grandma\'s lavender field had once been a purple sea. Now it was a few scraggly stalks. "Can\'t we just dig the well open?" Leo asked. Lumina shook her tiny head. "Opening it the wrong way would disturb the underground energy balance. First you need to find my Seal Stone from the well bottom and bring it to the Great Oak in the town center."',
      '"Where is the Seal Stone?" "At the bottom," Lumina sighed, "but the good news is — the well opening is sealed except for one fist-sized gap. Only a child\'s small hand can reach in." Zoe rolled up her sleeve and led Leo straight to the abandoned well.',
      'The well top was sealed with concrete, just as Lumina had said. Zoe reached through the gap, feeling around in the dark — until her fingers found something warm and carved with strange patterns. "Got it!" She carefully drew it out.',
      'They brought the Seal Stone to the Great Oak and pressed it into the soil at the roots. They waited. Nothing happened. Zoe\'s stomach sank. "One more thing," Lumina said. "The well needs a genuine wish to activate. What do you truly wish for, from the bottom of your hearts?"',
      'Zoe and Leo looked at each other. Zoe said quietly, "I wish for Maplewood\'s flowers to bloom again and for everyone to be happy." Leo added, "I wish for Grandma to get better. I wish every child in town could dream sweet dreams."',
      'The oak began to tremble. Orange light pulsed from its roots and spread through hidden underground channels in every direction — until the entire floor of Maplewood glowed faintly beneath them!',
      'Lumina lifted off from Zoe\'s hand and grew — from a tiny speck to a hand-sized fairy with orange wings and emerald eyes, radiant and joyful. "I\'m free!" she cried, spinning through the air.',
      'The next morning, Maplewood woke to a miracle: every flower in town had bloomed overnight. Lavender, roses, sunflowers, wild daisies — color and fragrance on every corner. Grandma\'s front yard was a purple sea again.',
      'From that day on, Zoe and Leo had a secret friend. Every night the streetlights still flickered — but now the message they spelled out was only two words: "Thank you."',
    ],
  },

  {
    id: 'star-captain',
    titleZh: '星际小队长',
    titleEn: 'Star Little Captain',
    descriptionZh: '银河学院最年轻的学员凯，在别人要消灭神秘访客时，发现了惊天真相——那些生命来自她父母失踪的那个星系。',
    descriptionEn: 'Cadet Kai, the youngest at the Galactic Academy, uncovers a shocking truth about mysterious crystal visitors no one else will listen to.',
    emoji: '🚀',
    category: 'space',
    categoryZh: '星际冒险',
    categoryEn: 'Space',
    gradient: 'from-indigo-500 via-blue-500 to-violet-600',
    paragraphsZh: [
      '宇宙历3052年，银河学院迎来了有史以来最小的学员——七岁的凯。她的飞船驾驶技术是全班最好的，但个子是最小的，坐进驾驶舱必须垫两个枕头才能够到控制台。大家都叫她"小豆丁"，她才不在意，因为她有一个梦想：成为最厉害的星际探险家。',
      '有一天，学院的食物花园里发生了大事。一群从未见过的小生物飞进来——它们大约手掌大小，翅膀透明得像水晶，身体散发着柔和的绿光，每一只都抱着一粒种子。学院安全警报立刻响了。',
      '院长严肃地宣布："这些未知生物正在侵入我们的食物花园！大家组成清除小队，立刻行动！"高年级学员们纷纷拿起装备，准备驱逐它们。',
      '凯站在走廊里，仔细看着花园里那些小生物。它们根本没有在破坏花园，而是在土地上轻轻打洞，把手里的种子一粒一粒放进去，再用翅膀扇出柔和的光为种子保温。它们的眼睛里有一种凯很熟悉的表情——思念。',
      '"等一下！"凯大声说，跑过去拦住了清除小队，"我觉得它们不是在破坏，它们是在种东西！"高年级队长皱起眉头，"你有什么证据？""因为，"凯说，"我认识那种眼神——那是想家的眼神。"',
      '凯放低身子，缓缓走向那些小生物。它们叫了两声，但没有逃走。凯蹲下来，仔细看了看它们种进土里的种子——上面有一种特殊的花纹，凯在星际植物图谱的角落里见过这个符号：那是遥远星系边缘的植物标记。',
      '她掏出翻译器，对准小生物，按下扫描键。翻译器显示出坐标数据——凯的心猛地一缩。那个坐标……是银河系边缘的一个小星系，距离这里需要飞行三年。',
      '那正是她父母执行任务时失踪的地方。',
      '"院长，"凯飞奔去找院长，"这些生物叫做晶翼兽，来自三年飞行距离之外的一个小星系。它们的星球因为我们学院的宇宙开发项目改变了轨道而正在死去。这批晶翼兽带着母星最后的种子来寻找新土地——它们是那个星球上最后的生命！"',
      '院长沉默了很久。"凯，你怎么能确定？"凯抬起头，眼神坚定，"因为翻译器里的坐标，就是三年前我父母发出最后一次信号的位置。"整个学院陷入了沉默。',
      '院长走向窗边，望着花园里那些轻轻扇动翅膀的小生物，很久，很久。终于，他低声说："我们犯了一个错误。在开发宇宙的时候，我们没有考虑到那些小小的生命。"',
      '院长转过身，声音庄重，"学院的决定：食物花园的一半空间，将永久留给晶翼兽，让它们在这里重建家园。银河学院将协助培育这些种子。"掌声响了起来，越来越大。',
      '晶翼兽们好像感应到了什么，全部飞向凯，用发光的翅膀轻轻包围她，温柔地振动。一阵暖意涌遍全身，凯的眼眶红了——也许，在某种意义上，她离父母更近了一步。',
      '几个月后，食物花园的那一半开出了全宇宙从来没人见过的花——七彩的、透明的、会随着心跳频率轻轻歌唱的花。晶翼兽在花丛中飞翔嬉戏，而凯，被学院授予了"最年轻的星际大使"称号。她在领奖台上只说了一句话："我希望有一天，能找到我的爸爸妈妈，告诉他们，那个星系的生命，没有消失。"',
    ],
    paragraphsEn: [
      'In the year 3052, the Galactic Academy welcomed its youngest cadet ever — seven-year-old Kai. She was the best pilot in her class, but also the smallest, and had to pile two cushions in the cockpit to reach the controls. Everyone called her "Little Bean." She didn\'t mind. She had a dream: to become the greatest space explorer alive.',
      'One day, something strange happened in the Academy\'s food garden. A swarm of unknown creatures flew in — each about the size of a palm, with crystal-clear wings and soft green glowing bodies, every one cradling a tiny seed. The security alarm shrieked to life.',
      'The headmaster announced grimly: "Unknown creatures are invading our food garden! All cadets — form a removal squad! Move out!" Older cadets grabbed their equipment and charged forward.',
      'Kai hung back in the doorway and watched carefully. The creatures weren\'t destroying anything. They were gently boring tiny holes in the soil, placing their seeds inside one by one, and fanning them with the warm glow of their wings. Their eyes held an expression Kai recognized immediately — homesickness.',
      '"Wait!" Kai ran forward and stepped between the removal squad and the creatures. "They\'re not attacking! They\'re planting!" The squad leader frowned. "What proof do you have?" "Because," Kai said quietly, "I know that look. That\'s the look of missing home."',
      'Kai crouched low and slowly approached the creatures. They chirped twice but didn\'t flee. She leaned close to examine one of the seeds — and spotted a symbol she\'d once seen in the very back of the Galactic Plant Atlas: the botanical marker for a star system at the far edge of the galaxy.',
      'She pulled out her translator, aimed it at the creatures, and pressed scan. The screen filled with coordinate data. Kai\'s heart seized. Those coordinates — that was the star system at the rim of the galaxy, three years of flight time away.',
      'The same place where her parents had disappeared.',
      '"Headmaster," Kai sprinted to find him, "these creatures are called Crystal Wings. They come from a small star system three years away. Their planet is dying — our Academy\'s development project altered its orbital path. These Crystal Wings carry the last seeds of their home world. They are the last living things from that planet!"',
      'The headmaster was quiet for a long time. "Kai, how can you be sure?" She lifted her eyes, steady and certain. "Because the coordinates on my translator are the exact location where my parents sent their last signal three years ago." The entire Academy fell silent.',
      'The headmaster walked to the window and looked out at the crystal-winged creatures gently tending their seeds. For a long time, he said nothing. Finally, he murmured, "We made a mistake. When we developed space, we didn\'t think about the small lives."',
      'He turned around, his voice solemn. "The Academy\'s decision: half the food garden will be permanently set aside for the Crystal Wings. We will help them rebuild their home." Applause broke out — growing louder and louder.',
      'The Crystal Wings seemed to sense what had happened. They all flew to Kai and surrounded her with their glowing wings, vibrating gently. A warmth filled her entire body, and her eyes stung. In some way she couldn\'t explain, she felt closer to her parents than she had in three years.',
      'Months later, that half of the food garden bloomed with flowers no one in the universe had ever seen — rainbow-colored, transparent, and humming softly in tune with a heartbeat. Crystal Wings danced among them. Kai was awarded the title "Youngest Galactic Ambassador." At the podium she said only one thing: "I hope someday I can find my parents, and tell them — the life from that star system did not disappear."',
    ],
  },

  {
    id: 'magic-library',
    titleZh: '魔法图书馆',
    titleEn: 'The Magic Library',
    descriptionZh: '月亮书院有个秘密：每晚月光照进圆窗，书里的角色就会走出来！新来的薇薇发现了一本被黑暗藤蔓缠绕、行将消失的书……',
    descriptionEn: 'Every night at Moon Academy, book characters come to life. New student Vivi discovers a beloved book being swallowed by dark vines — and only a remembered story can save it.',
    emoji: '📚',
    category: 'magic',
    categoryZh: '魔法世界',
    categoryEn: 'Magic',
    gradient: 'from-amber-500 via-orange-500 to-red-600',
    paragraphsZh: [
      '月亮书院有一个任何人来之前都不会知道的秘密。图书馆里，每天夜里月光从最高的圆窗照进来，书里的角色就会从书页里走出来，在走廊里活动整整两个小时。',
      '新来的学生薇薇那天夜里睡不着，悄悄溜进图书馆找书看，结果被眼前的场景惊呆了：孙悟空在书架顶上翻跟斗，哈利正和爱丽丝讨论各自遇到的奇怪生物，夏洛克·福尔摩斯拿着放大镜研究一盆植物。',
      '薇薇咬咬嘴唇，迈进了图书馆。孙悟空第一个发现了她，大叫一声："哇，真人！"所有角色立刻停下来盯着她。哈利走过来说："你是新来的？放心，我们不会咬人的。"爱丽丝补充道："大多数情况下不会。"',
      '"你们怎么会跑出来的？"薇薇问。孙悟空从书架跳下来，"俺们每天夜里都会出来活动活动，长期待在书里会长霉的！"他神气地抖了抖金箍棒，"话说，新来的小朋友，你叫什么名字？"',
      '就在这时，一阵哭声从书架深处传来。一个穿白裙子的小女孩跑出来——是安徒生童话里的小人鱼。她哭着说："我的书不见了！我明天没法回家了！"',
      '"书不见了？"薇薇皱起眉头。夏洛克走过来，弯腰检查小人鱼站过的地方，"有水迹，"他说，"以及，图书馆南角有异常。"他们循着水迹，来到图书馆最南角的一个蒙尘书架前。',
      '最高层，一本书在颤抖，发出微弱的蓝光。薇薇爬上书架——发现那本书被一根根细细的黑色藤蔓紧紧缠绕，无法打开。"这是影书藤，"孙悟空神情严肃，"它专门缠住那些快被遗忘的书，把书里的角色困住。"',
      '"被遗忘的书？"薇薇想了想，"所以，如果有人记住这本书，影书藤就没有力量了？""正是，"夏洛克点头，"你必须大声讲出书里的故事，让这个故事重新活在你心里。"',
      '薇薇接过那本颤抖的书，封面上的字已经模糊，但她努力辨认出一个词——"海"。她想了想，忽然想起奶奶曾经给她讲过一个关于大海的故事：一个为了真爱放弃了声音的哑公主，最终化作海上的泡沫，却获得了永恒的光……',
      '薇薇开始大声讲述。她的声音在图书馆里回响。黑色藤蔓开始颤抖，慢慢收缩。哈利说出他记得的一个片段，爱丽丝说出另一个，孙悟空虽然没读过，但他用金箍棒配合地敲打藤蔓。',
      '最后一根藤蔓断开了！书的封面突然变得清晰——《小人鱼》，安徒生著。小人鱼扑上去紧抱着书，哭了好久，"谢谢你，谢谢你，我可以回家了！"',
      '天边开始泛出鱼肚白，图书馆里的角色们一个个走回各自的书里。孙悟空最后一个消失，还不忘回头喊："以后多来看书！书里的我们都靠你们呢！"',
      '清晨，图书馆员进来，只看见薇薇坐在地上抱着一本《小人鱼》睡着了，脸上带着满足的微笑。她不知道的是，从那以后，每当有人翻开书页，书里会流过一道温暖的光——那是书中角色们，在感谢你记得他们。',
    ],
    paragraphsEn: [
      'Moon Academy had a secret no one told you before you arrived. In the library, every night when moonlight fell through the round high window, book characters stepped out of their pages and roamed the corridors for two full hours.',
      'New student Vivi couldn\'t sleep that night and crept into the library to find something to read — and stopped dead. Monkey King was doing somersaults on top of the bookshelves. Harry and Alice were debating their most bizarre encounters. Sherlock Holmes was examining a potted plant through his magnifying glass.',
      'Vivi bit her lip and stepped inside. Monkey King spotted her first. "A real person!" All the characters froze and stared. Harry walked over. "You must be new. Don\'t worry — we don\'t bite." Alice added, "Most of the time."',
      '"How are you out here?" Vivi asked. Monkey King leaped down from the shelf. "We come out every night for some fresh air! You\'d go moldy staying in a book forever!" He gave his staff a dramatic spin. "So, newcomer — what\'s your name?"',
      'Just then, crying came from deep in the stacks. A girl in a white dress ran out — the Little Mermaid from the fairy tales. She sobbed: "My book is gone! I can\'t get home tomorrow!"',
      '"A book can\'t just disappear," Vivi frowned. Sherlock crouched to examine the floor where the Little Mermaid had been standing. "Water trails," he said. "And there\'s an anomaly in the south corner." They followed the wet footprints to a dust-covered shelf at the back.',
      'On the highest shelf, one book trembled with a faint blue glow. Vivi climbed up — and found it wrapped in thin black vines that pulsed and tightened. "Shadow Vine," Monkey King said grimly. "It targets books that are nearly forgotten. Once it takes hold, the characters inside are trapped."',
      '"Nearly forgotten," Vivi murmured. "So if someone remembers the book — truly remembers it — the vines lose their power?" "Precisely," said Sherlock. "You must speak the story aloud. Make it live in your heart again."',
      'Vivi took the trembling book. The title had faded to almost nothing, but she made out one word: "Sea." She thought hard — and suddenly remembered her grandmother telling her a story about a mute princess who gave up her voice for love, and in the end became sea foam, but gained an eternal light...',
      'Vivi began to speak the story aloud. Her voice echoed through the library. The black vines quivered and shrank back. Harry recalled a fragment, Alice added another piece, and Monkey King — who had never read it — helped by whacking the vines with his staff.',
      'The last vine snapped. The book\'s cover became brilliant and clear: "The Little Mermaid, by Hans Christian Andersen." The Little Mermaid flung herself at the book and held it tight, crying. "Thank you, thank you — I can go home!"',
      'The eastern sky was beginning to lighten. One by one the characters stepped back into their books. Monkey King was last, and he called back as he faded: "Keep reading books! We all depend on you!"',
      'In the morning the librarian found Vivi sitting on the floor, asleep, hugging a copy of The Little Mermaid, a peaceful smile on her face. What Vivi didn\'t know was that from that night on, whenever anyone opened a book, a warm light moved through the pages — the characters inside, saying thank you for remembering them.',
    ],
  },

  {
    id: 'great-wall',
    titleZh: '长城守护者',
    titleEn: 'Guardian of the Great Wall',
    descriptionZh: '八岁的小梅触碰了长城上一块神奇的古石砖，穿越到了汉朝，遇见了同龄的女孩云儿——两个时代的孩子，共同守护一个关乎千人生命的秘密。',
    descriptionEn: 'When Mei touches an ancient stone on the Great Wall, she crosses into the Han Dynasty and meets a girl named Yun — and together, across time, they must protect a secret that could save thousands.',
    emoji: '🏯',
    category: 'history',
    categoryZh: '历史传说',
    categoryEn: 'History',
    gradient: 'from-red-500 via-orange-500 to-yellow-500',
    paragraphsZh: [
      '八岁的小梅第一次来到长城，就觉得这里不太对劲。不是说长城不壮观——长城当然壮观极了，连绵的城墙像一条巨龙趴在山脊上。但她总觉得，最古老的那段城墙在盯着她看，尤其是一块刻着奇怪花纹的石砖。',
      '同学们都去拍照了，只有小梅停在那块石砖前。花纹似乎在动……她伸出手，碰了碰——嗡的一声！一道蓝光把她包围，意识飘离了身体，眼前的世界开始旋转……',
      '等她再睁开眼，景象全变了。长城还在，但破旧了许多，空气里有炊烟和风沙的气息。路过的人穿着古代的衣服，士兵扛着长枪巡逻。小梅呆呆地站着，不知所措。',
      '"你是谁？"一个清脆的声音把她吓了一跳。她转过身，看见一个和她差不多大的女孩，扎着两个小丫髻，一双眼睛亮得像星星。"我……我叫小梅，"小梅结结巴巴地说，"你呢？""我叫云儿，"女孩拉着她的手，"快跟我来！长城上不准闲人走动！"',
      '云儿把小梅带进城墙里的一个小空间，里面有草席、火炉和几本书。"这是我爹的宿舍，他是这段城墙的石匠班头，"云儿解释说，然后好奇地打量小梅，"你的衣服好奇怪。你从哪里来的？"',
      '小梅决定说实话："我是从一千多年后来的，现代人。"云儿没有表现出太多惊讶，只是点了点头，"那块石砖我爹说过，是几百年前一位术士留下的，能连接不同的时代。想必是真的。"',
      '"那我能回去吗？"小梅问。"等到明天同一时刻，石砖再次发光，"云儿说，然后表情变得严肃，"但我需要你的帮助。出了很大的麻烦。"',
      '云儿解释道：她父亲在一块特制城砖里藏了一份和平盟约，若这盟约能送到京城，可以避免一场将让数千人流离失所的大战。但官府里有个贪官想要发战争财，正派人搜查，威胁她父亲。他们需要想办法在今晚之前，让盟约的消息传出去。',
      '"我们是两个小孩，没有人会信我们，"云儿说，"而且跑去京城也太慢了。"小梅苦苦思索，突然想到了什么，"等等——你爹把盟约藏在城砖里……如果我们在城砖上留下特殊的标记，一千多年后，有人研究这块砖的时候，他们会发现！"',
      '"一千年后？"云儿皱眉，"那也太慢了……"小梅说："但那是真实存在的证据！而且，当我回到我的时代，我可以把这件事告诉考古学家，让他们来研究这块砖！那样的话，盟约的存在——包括那个贪官的罪行——都会被查清楚！"',
      '云儿想了很久，终于点头，"好。就这么做。"她拿出小刀，在存放盟约的城砖旁边刻下了一行古字，描述盟约的位置和贪官的名字。小梅也用指甲在旁边刻下了两个现代字："小梅"。',
      '第二天同一时刻，那块石砖再次发光，小梅被送了回来。她发现自己还站在原地，同学们还在拍照，好像时间从未流动。',
      '但是那块石砖上，多了两种字迹：一行古汉字，和旁边两个现代字——"小梅"。小梅用手指轻轻摩挲那两个字，眼眶湿润了。她知道这意味着什么：云儿他们成功了。',
      '回家后，小梅在历史书里反复查找，终于在一本古籍记载中找到了：汉朝某年，长城石匠藏入城砖的和平文书被发现，战事因此平息，千余人得以安居。文书旁还有两行刻字，史学家们百思不得其解——一行古汉字，一行却是令人费解的"小梅"。',
    ],
    paragraphsEn: [
      'The first time eight-year-old Mei visited the Great Wall, she sensed something was strange. Not that the Wall wasn\'t magnificent — it was breathtaking, stretching over the mountains like a sleeping dragon. But the oldest section seemed to be watching her, especially one stone block carved with unfamiliar patterns.',
      'Her classmates ran off to take photos. Mei stayed. The carved patterns seemed to shift. She reached out and touched them — a deep hum filled the air, blue light wrapped around her, and the world spun away...',
      'When she opened her eyes, everything had changed. The Wall was still there, but rougher and older. The air smelled of cooking smoke and wind-blown sand. People in ancient clothing walked past; soldiers patrolled with long spears. Mei stood frozen, completely lost.',
      '"Who are you?" A bright voice made her jump. A girl about her age stood there, hair in two small buns, eyes shining like stars. "I\'m... I\'m Mei," she stammered. "And you?" "My name is Yun," the girl said, grabbing her hand. "Come with me! Civilians aren\'t allowed on the Wall!"',
      'Yun led her into a small space inside the Wall — a sleeping mat, a stove, a few books. "This is my father\'s quarters. He\'s the head stonemason for this section," Yun explained, looking curiously at Mei\'s clothes. "You dress so strangely. Where are you from?"',
      'Mei decided to tell the truth. "I\'m from over a thousand years in the future." Yun didn\'t look very surprised. "Father said that stone block was left by a sorcerer centuries ago — that it connects different times. I suppose he was right."',
      '"Can I get back?" Mei asked. "When the stone lights up again tomorrow at the same time," Yun said. Then her expression grew serious. "But I need your help. Something very bad is happening."',
      'Yun explained: her father had hidden a peace treaty inside a specially carved Wall stone. If that treaty reached the capital, it would prevent a war that would displace thousands of people. But a corrupt official who wanted the war for profit was searching for it and threatening her father. They needed to get word out tonight.',
      '"We\'re just two children. Nobody will believe us," Yun said. "And running to the capital would take too long." Mei thought hard — then sat up straight. "Wait. Your father hid the treaty inside a Wall stone. What if we carve special marks on the stone? More than a thousand years from now, when archaeologists study these bricks, they\'ll find them!"',
      '"A thousand years from now?" Yun frowned. "That\'s so slow —" "But it\'s real, permanent evidence!" Mei said. "And when I go back to my time, I can tell archaeologists to look for exactly this stone. They\'ll find the treaty, and proof of the corrupt official\'s crimes, all at once!"',
      'Yun thought for a long time, then nodded. "All right. Let\'s do it." She took out a small knife and carved a line of ancient text beside the stone where the treaty was hidden — describing its location and the official\'s name. Mei used her fingernail to carve two marks of her own beside it: her name.',
      'The next day at the same hour, the carved stone lit up and Mei was returned. She found herself standing exactly where she\'d been, classmates still posing for photos, as though no time had passed at all.',
      'But the ancient stone now had two sets of markings: a line of Han Dynasty characters, and beside them — Mei\'s name. She traced the letters with her fingertip, eyes stinging. She knew what it meant: Yun had succeeded.',
      'Back home, Mei searched through history books for weeks. Finally, in an old chronicle, she found it: in the Han Dynasty, a stonemason\'s hidden peace treaty was discovered inside a Wall stone, bringing a conflict to an end and saving thousands of people. Beside the treaty, two carved inscriptions mystified historians for centuries — one in ancient Chinese, and one that read, inexplicably, "Mei."',
    ],
  },

  {
    id: 'super-heroine',
    titleZh: '超能小英雄',
    titleEn: 'The Super Little Heroine',
    descriptionZh: '超能学院里，小璐的超能力只有一个：倒着飞。被同学嘲笑的她，却在最关键的时刻，用这个"没用"的力量拯救了所有人。',
    descriptionEn: 'At the Super Academy, Luna can only fly backwards. Everyone laughs — until a runaway truck shows that flying backwards might be the most powerful ability of all.',
    emoji: '🦸‍♀️',
    category: 'superhero',
    categoryZh: '超级英雄',
    categoryEn: 'Superheroes',
    gradient: 'from-rose-500 via-pink-500 to-fuchsia-600',
    paragraphsZh: [
      '超能学院每年只录取十名拥有特殊能力的学生。今年的十人里，小璐的超能力最特别——她能飞，但只能倒着飞。',
      '倒着飞，也就是说，她的正脸朝的那个方向，其实是她要离开的方向。她想向右转，就必须向左倾。她想降落，就必须往上用力。这导致她无数次撞上墙壁，撞上树，有一次还撞上了食堂的大广告牌。',
      '其他同学的超能力听起来厉害多了：小铁能变成各种形状的金属，小花能召唤和控制植物，小闪能跑得比光快，小力拥有无限的气力……只有小璐，靠着一个奇怪的倒飞能力，感觉像个笑话。',
      '体能课上，教练设置了第一个任务：飞越训练场的障碍墙。小闪一眨眼就飞过去了，小花用植物藤蔓当弹床轻盈越过，小铁把自己变成了小飞机穿越障碍。轮到小璐，她起飞——嘭！迎面撞上第一块板，大家憋着笑。小璐爬起来，深吸一口气，转过身，背对着终点起飞，成功越过了障碍墙！但是等她到达终点时，她正面朝着的是起点方向。',
      '"……也算完成了，"教练无奈地说。小璐红着脸坐回去，有点想哭。',
      '下课后，小璐独自坐在训练场角落。这时，她发现操场对面出了状况——搬运工正在运送建材，一辆重型货车突然刹车失灵，正向下坡冲去！下坡尽头，一群幼儿园小朋友正在休息！',
      '其他同学都在食堂，来不及了！小璐腾空而起，但她飞向了相反方向……她在心里飞速计算：如果我背对着货车、倒着飞向货车，对我来说就是往我的"正方向"走——等等，这样能行！',
      '她翻了个身，背对着货车，倒着全速冲去。在外人看来，她的脸朝着相反方向，但她以最快的速度冲向了失控的货车，在货车即将碰上孩子们的一刹那，用双手死死顶住了车头！',
      '货车停下来了。孩子们毫发无伤，尖叫着跑向老师。',
      '大家从食堂冲出来，围住了小璐。她的手掌磨破了，头发乱糟糟的，但她咧嘴笑着。教练皱着眉头，"你是怎么做到的？你的速度比平时快了三倍——"小璐耸耸肩，"因为对我来说，那是我的「正面方向」，所以我能达到最大速度。"',
      '小闪沉默了一下，"所以，如果我们遇到需要从背面偷袭的情况……""或者在狭窄的地方需要快速退出……""或者让对手永远猜不到我们从哪个方向来……"同学们七嘴八舌地说起来。',
      '教练脸上浮现出一个神秘的微笑，"小璐，你知道超能学院有史以来最厉害的毕业生之一是谁吗？她叫「回旋镖」，她唯一的能力是——扔出去的任何东西都会绕圈回来。大家最初都说她的能力没用，但她后来成为了最擅长迂回战术的英雄，每次她冲进去的时候，其实是在绕后。"',
      '小璐楞了一下，然后笑了——从心底里，慢慢地笑了起来。"倒着飞的意思，"教练说，"不是走的路错了，而是你看见了别人看不见的那一面。"',
      '从那以后，超能小队有了给小璐专门留的位置：每当队伍向前冲的时候，小璐从侧翼倒飞，悄悄绕到对手的背后——而对手，永远不知道那个从意想不到的方向扑来的身影，就是她们最危险的存在。',
    ],
    paragraphsEn: [
      'The Super Academy only accepted ten students with special abilities each year. Of this year\'s ten, Luna had the most unusual power of all — she could fly. But only backwards.',
      'Flying backwards meant the direction her face pointed was actually the direction she was leaving. To turn right she had to lean left. To land she had to push upward. This caused her to crash into walls, trees, and on one memorable occasion, the cafeteria\'s enormous sign.',
      'Everyone else\'s powers sounded so impressive: Iron could become any shape of metal; Flora could summon and control plants; Flash could run faster than light; Force had unlimited strength. Only Luna, with her baffling reverse-flight, felt like a joke.',
      'In PE class, the instructor set the first challenge: fly over the obstacle wall. Flash crossed in a blink; Flora bounced off plant vines; Iron turned into a tiny plane. Then it was Luna\'s turn. She launched — and smashed straight into the first panel. Suppressed laughter from all sides. Luna got up, took a breath, turned around, and flew backwards — and cleared the wall. But she arrived at the finish line facing the wrong direction.',
      '"...I\'ll call that a pass," the instructor said tiredly. Luna sat down, cheeks burning, fighting tears.',
      'After class, Luna sat alone in the corner of the training yard. Then she spotted trouble across the field. Workers were unloading materials when a heavy truck\'s brakes failed — it was rolling down the slope, picking up speed. At the bottom of the slope, a group of kindergarteners sat resting.',
      'The others were all in the cafeteria. There was no time! Luna shot into the air — and flew in the wrong direction. But mid-flight her mind raced: if I face away from the truck and fly backwards toward it, then for me, I\'m flying in my forward direction... and I can go full speed!',
      'She flipped around, back to the truck, and blasted toward it at maximum velocity. From the outside, her face was pointing away from the truck. But she hit it head-on, palms first, at three times her normal speed — stopping it cold just as it was about to reach the children.',
      'The truck stopped. The children were unharmed, shrieking as they ran to their teachers.',
      'Everyone poured out of the cafeteria. Luna\'s palms were scraped raw and her hair was a mess, but she was grinning. The instructor frowned. "How did you do that? Your speed was three times normal —" Luna shrugged. "Because for me, that was my forward direction. I can only go full speed going backwards."',
      'Flash was quiet for a moment. "So if we ever need to attack from behind..." "Or exit a tight space fast..." "Or hit from a direction nobody expects..." The team started talking over each other.',
      'The instructor\'s eyes lit with a slow smile. "Luna, do you know who one of the greatest graduates in Super Academy history is? Her name is Boomerang. Her only power was that anything she threw always came back. Everyone said it was useless. But she became the greatest master of indirect tactics — every time she charged in, she was actually going around the back."',
      'Luna blinked — and then smiled. Slowly, from deep inside, she smiled. "Flying backwards doesn\'t mean going the wrong way," the instructor said. "It means you see the side nobody else can."',
      'From that day on, the Super Squad had a permanent role for Luna: whenever the team charged forward, Luna flanked from the side, circling silently to the back — and the opponent never knew that the figure arriving from the most unexpected direction was the most dangerous one of all.',
    ],
  },

  {
    id: 'time-traveler',
    titleZh: '时间旅行者',
    titleEn: 'The Time Traveler',
    descriptionZh: '七岁的诺诺在阁楼找到了一块神奇的怀表——表盘里显示的不是时间，而是过去真实发生的画面。但怀表正在消失，拯救它的方法……只有真诚的感谢。',
    descriptionEn: 'Nora finds a pocket watch that shows images from the past — but it\'s fading away, and the only thing that can save it is genuine, heartfelt gratitude.',
    emoji: '⏰',
    category: 'space',
    categoryZh: '星际冒险',
    categoryEn: 'Space',
    gradient: 'from-violet-500 via-purple-500 to-indigo-600',
    paragraphsZh: [
      '暑假第一天，七岁的诺诺在阁楼上翻到了一个旧木盒。木盒里有一块银色的怀表，表壳上刻着一朵小花。打开表盖，里面不是普通的表盘，而是一块模糊的小屏幕，像一台超小的电视机。',
      '"妈妈，这是什么？"诺诺跑下楼问。妈妈看了一眼，表情有些奇怪，"这是你太祖母留下来的，我们谁都不知道怎么用。"说完便回了厨房，好像不太想继续聊。',
      '诺诺好奇地打开怀表——里面的影像突然变得清晰！她看见一个穿古代衣服的小女孩在院子里玩，院子里有棵大柿子树……影像消失了。诺诺合上再打开，每次都是不同的画面：帆船在大海上搏浪，商人骑骆驼穿越沙漠，黑白街道上有一个女孩在奔跑……',
      '诺诺发现了规律：怀表打开的时间越长，影像越清晰。而且，如果她说"谢谢"，影像里的人好像能感应到，会朝她的方向望一眼。这块怀表，连接着真实的过去！',
      '但问题出现了：有一天，她打开怀表，发现影像变暗了，颜色越来越浅，像一张褪色的照片。怀表开始轻轻震动——好像在报警！',
      '一个老奶奶的声音从怀表里传出来，微弱而急切："孩子……怀表的能量快耗尽了……里面的记忆会消失……你必须完成三件事，为它充能……"声音断了，留下了三条任务。',
      '第一件事：去学校，向那个每天帮大家擦黑板却从来没有人谢过的清洁阿姨，说一声谢谢。第二件事：去奶奶家，为两年前打碎了奶奶最喜欢的茶杯却偷偷逃跑一事，认真地道歉。第三件事：去爸爸的办公室，告诉他，你知道他每天工作很辛苦，你爱他。',
      '诺诺把三件事都列在纸上。说起来容易，做起来难——她去学校时，在走廊里走了三个来回，才鼓起勇气走到清洁阿姨面前，"阿姨，谢谢你每天帮我们擦黑板。"',
      '清洁阿姨愣了好久，眼眶慢慢红了，低声说："谢谢你，孩子。这么多年，没有人说过这句话。"诺诺也跟着眼眶热了。',
      '去奶奶家道歉更难——那只茶杯是奶奶的宝贝。诺诺低着头，把那件事一字一字地说了出来。奶奶沉默了一会儿，然后拉起她的手说："你知道那只杯子里装着什么吗？里面装着你妈妈小时候给我画的一张画。可是，能换来你今天这句话，这茶杯碎得值了。"',
      '最难的是去爸爸办公室。诺诺站在爸爸办公室门口，举起手要敲门，举了三次才敲下去。爸爸出来了，一脸疑惑。诺诺深吸一口气，"爸爸，我知道你每天工作很辛苦。我爱你。"爸爸把她抱了很久很久，久到她都有点喘不过气来。',
      '做完三件事，诺诺的心里有一种奇妙的感觉，轻飘飘的，暖融融的。她打开怀表——',
      '怀表大放光明！影像变得前所未有地清晰。她看见了一个穿旗袍的老太太，正在书桌前用毛笔写字。老太太抬起头，好像真的看见了诺诺，露出了慈爱的微笑，嘴里无声地说着什么。',
      '"太祖母？"诺诺轻声问。老太太点了点头，嘴形说的是：谢谢你，记得我们。影像慢慢消失，怀表的小屏幕变成了普通的表盘，开始走动——嘀嗒嘀嗒。但在表壳内侧，诺诺发现了一行毛笔小字："时光留不住，但感恩使它长存。——祖"',
      '从那以后，诺诺每天都认真地对身边的人说谢谢。她不知道怀表里的记忆是否都被保住了，但她知道——每一次真诚的感谢，都是送给时光最好的礼物。',
    ],
    paragraphsEn: [
      'On the first day of summer vacation, seven-year-old Nora was rummaging in the attic when she found an old wooden box. Inside was a silver pocket watch engraved with a tiny flower. She opened the cover — and instead of a clock face, found a small screen, fuzzy like a tiny television.',
      '"Mom, what\'s this?" She ran downstairs. Her mother looked at it, expression strange. "It belonged to your great-great-grandmother. None of us ever figured out how it works." Then she went back to the kitchen, as though she didn\'t want to talk about it.',
      'Nora opened the watch again — and the image inside suddenly sharpened. A girl in ancient clothes played in a courtyard beneath a persimmon tree... then it faded. Nora snapped it shut and reopened it. A different scene: sailors battling waves at sea. A merchant crossing a desert by camel. A girl running down a black-and-white city street.',
      'She noticed a pattern: the longer she held the watch open, the clearer the image became. And when she said "thank you," the people in the images seemed to sense it — they would glance in her direction. This watch was connected to the real past!',
      'Then the problem: one morning she opened the watch and the images had dimmed, colors bleached pale like a faded photograph. The watch began to tremble gently — like an alarm.',
      'A weak, urgent old voice drifted from inside: "Child... the watch is running out of energy... the memories inside will disappear... you must complete three things to restore it..." The voice cut out, leaving behind three tasks.',
      'First: go to school and thank the cleaning lady who wipes the blackboards every day — the one nobody has ever thanked. Second: go to Grandma\'s house and properly apologize for breaking her favorite teacup two years ago and sneaking away without saying anything. Third: go to Dad\'s office and tell him you know how hard he works every day, and that you love him.',
      'Nora wrote all three tasks on a piece of paper. Easy to write. Hard to do. At school she walked back and forth down the hallway three times before she finally gathered the nerve to approach the cleaning lady. "Auntie, thank you for wiping our blackboards every day."',
      'The cleaning lady stared for a long moment. Then her eyes filled. "Thank you, child," she said quietly. "In all these years, no one has ever said that." Nora\'s own eyes stung.',
      'Apologizing to Grandma was harder. That teacup had been her treasure. Nora stood with her head bowed and said every word slowly. Grandma was quiet — then took Nora\'s hand. "Do you know what was in that teacup? A drawing your mother made for me when she was little. But if it gives me this from you today, it was worth breaking."',
      'The hardest was Dad\'s office. Nora stood at the door, hand raised to knock, and lowered it three times before finally knocking. Dad came out, puzzled. Nora took a deep breath. "Dad. I know you work really hard every day. I love you." Dad held her for a very long time — so long she could barely breathe.',
      'After all three tasks were done, Nora felt something strange settle in her chest: warm and floating, like a sigh. She opened the watch.',
      'It blazed with light! The image inside was clearer than she had ever seen. She saw an old woman in a qipao dress sitting at a writing desk, brushing Chinese characters. The woman looked up — looked directly at Nora — and gave her a warm, knowing smile. Her lips moved without sound.',
      '"Great-great-Grandmother?" Nora whispered. The old woman nodded. Her lips said: thank you for remembering us. The image faded. The small screen became a normal clock face and began to tick — tick-tock, tick-tock. But on the inside of the cover, Nora found a line written in brushstrokes: "Time cannot be kept — but gratitude makes it last forever. — Ancestor."',
      'From that day on, Nora thanked the people around her every single day. She didn\'t know whether all the memories in the watch had been saved. But she knew this: every genuine thank-you is the best gift you can give to time.',
    ],
  },

  {
    id: 'ocean-messenger',
    titleZh: '深海使者',
    titleEn: 'Messenger from the Deep',
    descriptionZh: '玛丽娜从小就能听见大海的歌声。那年夏天，歌声变得急促悲伤——她发现礁石深处有一只被渔网困住的海洋精灵，正在等待拯救。',
    descriptionEn: 'Marina has always been able to hear the ocean singing. But one summer the song turns urgent and sad — a trapped ocean sprite needs her help, and she\'ll have to rally seagulls, crabs, and even a whale to save it.',
    emoji: '🌊',
    category: 'ocean',
    categoryZh: '深海奇旅',
    categoryEn: 'Ocean',
    gradient: 'from-cyan-500 via-teal-500 to-blue-600',
    paragraphsZh: [
      '玛丽娜从来没有见过大海，但她总是能听见大海的歌声。不管走到哪里，只要捡起一只贝壳放到耳边，她就能听见遥远的、悠扬的旋律，像妈妈哼的摇篮曲，又像风穿过芦苇丛的声音。',
      '今年夏天，全家搬到了海边小镇。玛丽娜终于看见了真正的大海——那片蔚蓝无边的水，比她想象的还要壮阔。但是今天，大海的歌声不对劲了——它急促、哀怨，像在哭泣。',
      '玛丽娜沿着礁石走，听着歌声越来越清晰。她发现，歌声是从一个深在礁石缝里的水洼里传出来的。她爬过去，弯下腰——',
      '水洼里有一个巴掌大小的小精灵，浑身闪着珍珠色的光，长着鱼尾，头上戴着一顶用海草编的小王冠。它看见玛丽娜，立刻停止了歌唱，用两只大眼睛盯着她。',
      '"你是海洋精灵吗？"玛丽娜轻声问。精灵点了点头，"我叫珍珠，我是这片海湾的使者。一个星期前，一张被人类遗弃的旧渔网漂进了礁石缝，缠住了我的鱼尾。我一直在唱歌求救，但没有人听见——直到你来了。"',
      '玛丽娜仔细看了看，渔网的细丝果然缠着珍珠的尾巴。但渔网太细，用手不好解开，而且如果拉错方向，会伤到珍珠。玛丽娜需要帮手。她环顾四周——岩石上有几只螃蟹，天空中有海鸥在盘旋，远处一头大鲸鱼跃出了水面。',
      '"我们来想想办法，"玛丽娜说。她在地上捡了几粒彩虹贝壳，轻轻放在一只大螃蟹面前，"我可以用这些贝壳换你帮我的忙吗？"大螃蟹侧着脑袋看了看贝壳，夹了夹钳子，算是同意了。',
      '螃蟹的钳子灵巧极了，它很快找到了渔网打结的地方，一点一点地解开。但最后一个死结太紧，螃蟹的力气不够了。玛丽娜抬头，对着盘旋的海鸥学着吹口哨，两只海鸥落了下来。玛丽娜用手比划，它们好像明白了，用尖嘴啄了起来。但渔网的材质太硬，嘴啄不断。',
      '珍珠的声音越来越弱，水洼里的水开始蒸发。玛丽娜急得直转圈……忽然，她想到了什么。她转向大海，大声唱起歌来——是妈妈教她的那首关于大海和帆船的儿歌。',
      '远处的大鲸鱼扭过身子。它的眼睛缓缓转向玛丽娜，如同两块深蓝色的宝石。慢慢地，鲸鱼游了过来，在礁石外停下。然后——嗖！喷出了一大股水柱，精准地落在渔网上！海水把渔网泡胀了，螃蟹趁机再次用力……渔网断了！',
      '珍珠自由了！她一跃而起，在玛丽娜眼前飞旋了三圈，然后纵身跳入大海。玛丽娜担心地望着，但珍珠很快探出头来，脸上是大大的笑容，全身的珍珠色光泽比以前更亮了。',
      '"谢谢你，玛丽娜，"珍珠说，"你愿意听一个秘密吗？你从小就能听见大海的歌声，是有原因的——我们海洋精灵，会把摇篮曲唱给那些心地善良的孩子们听。从你出生起，我就一直在唱。"',
      '"是你？！"玛丽娜瞪大了眼睛。珍珠微笑着点头，"所以，是你救了我，也是你救了你自己的那首歌。大海喜欢你，小朋友。"',
      '玛丽娜坐在礁石上，望着大海，听着大海重新歌唱——这次，歌声是欢快的，轻盈的，像在说：谢谢你。而玛丽娜把手放在胸口，感受着大海的心跳，第一次觉得，她找到家了。',
    ],
    paragraphsEn: [
      'Marina had never seen the ocean before, but she had always been able to hear it singing. Wherever she went, if she picked up a seashell and held it to her ear, she could hear a distant, floating melody — like her mother humming a lullaby, or wind drifting through reeds.',
      'This summer, her family moved to a seaside town. Marina finally saw the real ocean — a vast, brilliant blue stretching to the horizon, more magnificent than she had ever imagined. But today, the ocean\'s song was wrong. It was urgent and sorrowful, like weeping.',
      'Marina followed the sound along the rocky shore. The singing grew clearer near a water pool caught in the crevice of a deep reef. She climbed over and leaned down to look.',
      'Inside the pool was a creature the size of her palm, glowing in soft pearl-light, with a fish tail and a tiny crown woven from sea grass. It spotted Marina and fell silent, staring up at her with two very large eyes.',
      '"Are you an ocean fairy?" Marina whispered. The creature nodded. "My name is Pearl. I\'m the messenger of this bay. One week ago, an abandoned fishing net drifted into the reef and tangled around my tail. I\'ve been singing for help — but no one could hear me. Until you came."',
      'Marina looked closely. Fine net threads were indeed wrapped around Pearl\'s tail. The net was too delicate to untangle by hand without risking injury. She needed help. She looked around: crabs on the rocks, seagulls circling overhead, and in the distance a huge whale leaping from the surface.',
      '"Let\'s think this through," Marina said. She gathered a handful of rainbow shells from the ground and placed them gently before the largest crab. "Can I trade these for your help?" The crab tilted its head, snapped its claws, and agreed.',
      'The crab\'s pincers were remarkably precise. It found the net\'s knot and worked it loose, bit by bit. But the final knot was too tight for its strength. Marina looked up, tried to whistle at the circling seagulls, and two landed beside her. She gestured — they seemed to understand and pecked at the knot with their sharp beaks. But the net material was too tough to snap.',
      'Pearl\'s voice was growing faint; the water in the pool was slowly evaporating. Marina paced frantically — then something came to her. She turned toward the open sea and began to sing — the song about the ocean and sailboats that her mother had taught her.',
      'The distant whale rotated toward her. Its eyes — two deep-blue gems — turned slowly in Marina\'s direction. Slowly, the whale swam closer and stopped just beyond the reef. Then — whoosh! It spouted a great column of water that fell precisely on the fishing net. The net swelled with seawater; the crab seized its chance and pulled with all its might... the net snapped!',
      'Pearl was free! She leaped up, spun three times before Marina\'s eyes, then plunged into the sea. Marina watched anxiously — but Pearl\'s head popped up almost immediately, beaming, her pearl-light shining brighter than ever.',
      '"Thank you, Marina," Pearl said. "Would you like to hear a secret? There\'s a reason you\'ve always been able to hear the ocean\'s song — we ocean fairies sing lullabies to children with kind hearts. I\'ve been singing to you since the day you were born."',
      '"That was you?!" Marina\'s eyes went wide. Pearl smiled and nodded. "So you rescued me — and you also rescued your own song. The ocean loves you, little friend."',
      'Marina sat on the rocks and listened as the ocean sang again — joyful now, light and dancing, as if to say: thank you. She put her hand on her chest, felt the rhythm of the waves, and for the very first time, felt that she had come home.',
    ],
  },

  {
    id: 'mulan-legacy',
    titleZh: '木兰的传承',
    titleEn: "Mulan's Legacy",
    descriptionZh: '花悦是花木兰的曾孙女，她不喜欢武术，只爱音乐。但当她发现偷粮食的竟然是一群饥饿的孤儿，她决定用音乐做武器，做一件真正勇敢的事。',
    descriptionEn: 'Hua Yue is Mulan\'s great-granddaughter who loves music, not fighting. When she discovers the food thieves are starving orphans, she uses her music to help them — and learns what true courage really means.',
    emoji: '🌺',
    category: 'history',
    categoryZh: '历史传说',
    categoryEn: 'History',
    gradient: 'from-red-500 via-rose-500 to-pink-600',
    paragraphsZh: [
      '花悦是花木兰的第十代曾孙女，住在一个普通的小镇上。她知道自己有一个传奇的祖先，但她一点儿也不觉得自己传奇——她不会武功，也不喜欢练武，她最喜欢的事情是弹古筝、拉二胡，还有唱那些奶奶教她的古老民谣。',
      '有一天，镇上出了大事：粮仓里的粮食连续三天在深夜被偷走，小偷行动极快，大家都抓不住。村长急得团团转，镇上的成年人们开始轮流守夜。',
      '花悦看着这一切，心里想：如果是祖先花木兰，她会怎么做呢？出去巡逻打架？可她才八岁，也不会武功。跑去告诉大人？可她没有任何线索。思来想去，花悦做了一个别人都没想到的决定。',
      '当天夜里，她独自爬上了粮仓旁边的屋顶，带着她的二胡。她把耳朵贴在屋顶上，静静地等待着……',
      '子夜时分，她听见了脚步声——轻，碎，慌乱。不像强盗，倒像是很多很多双小脚。花悦悄悄从屋顶边探出头，月光下，她看见了十几个孩子，最大的十岁，最小的只有三四岁，每个人都饿得面黄肌瘦，正在粮仓门口往口袋里装粮食。',
      '花悦心里一紧——这些都是孩子！她没有大喊，没有报警，而是慢慢拿起了二胡，轻轻拉起来。',
      '夜风里，二胡的声音悠扬地飘出来——哀而不伤，缓缓流淌。孩子们愣住了，一个个停下手，四处张望寻找声音的来源。花悦站在月光下的屋顶上，拉了一首奶奶教她的古老民谣，那是一首关于流浪与归家的歌。',
      '孩子们放下了口袋。有一个小女孩开始哭泣。最大的那个男孩慢慢举起手，做出投降的手势，声音颤抖着说："别告诉大人，求你了。我们……我们只是太饿了。"',
      '花悦从屋顶爬下来，坐到孩子们中间。"你们是哪里来的？"她轻声问。男孩犹豫了一下，说出了实情：他们是邻镇的孤儿，家乡遭了旱灾，被好心人送到城里，但负责照顾他们的大人突然失踪了。他们已经三天没有吃东西了。',
      '花悦站起来，做了一个决定。她敲响了村长家的门。村长看见她，睡眼惺忪，"花悦？大半夜的——"花悦说："村长伯伯，我找到小偷了。但是……您能先听我说完吗？"',
      '村长听完，脸色变了又变。他出来，看着那群饿得发抖的孩子们，长叹了口气，"我还以为是什么大盗……"花悦说，"我有个办法。明天镇上有庙会，我去表演，把赚到的钱换成粮食给他们。然后我再帮他们联系政府，找到正规的安置。"',
      '村长看着眼前这个八岁的女孩，想起了镇上人讲的花木兰的故事，笑了，"好，你去。我来帮你。"',
      '第二天庙会上，花悦的二胡吸引了越来越多的听众，掌声阵阵，红包不断。镇上的大人们知道了孩子们的遭遇后，纷纷捐出粮食和衣物。很快，孤儿们有了热饭，有了棉衣，政府的工作人员也来了，帮他们找到了正规的儿童之家。',
      '那个最大的男孩临走前，拉住花悦的手说，"我们不知道你叫什么名字。""我叫花悦，"她说。男孩点点头，"花悦姐姐，谢谢你。你不像英雄，但你做了英雄做的事。"花悦笑了笑，"我有一个很厉害的祖先，她教会了我——真正的勇气，用心就够了，不一定非要用剑。"',
    ],
    paragraphsEn: [
      'Hua Yue was the tenth-generation great-granddaughter of Hua Mulan, living in an ordinary town. She knew her ancestor was legendary — but she didn\'t feel legendary herself at all. She had no interest in martial arts. What she loved was playing the guzheng, drawing the erhu bow, and singing the old folk songs her grandmother had taught her.',
      'One day, the town was in an uproar: someone had been stealing grain from the storehouse for three nights running. The thief moved so fast that no one could catch them. The village chief was beside himself, and the adults took turns keeping watch through the night.',
      'Hua Yue watched all of this and thought: what would my ancestor Mulan have done? Go out and fight? But she was eight years old and had no fighting skills. Tell the adults? She had no clues. After thinking it through, she made a decision nobody else had considered.',
      'That night, she climbed alone onto the roof beside the storehouse, erhu in hand. She pressed her ear to the roof and waited, quietly.',
      'At midnight, she heard footsteps — light, quick, and anxious. Not the sound of a thief. More like many small feet. Hua Yue peeped over the edge of the roof. In the moonlight, she saw over a dozen children: the oldest around ten, the youngest only three or four, all of them pale with hunger, frantically filling pouches with grain.',
      'Hua Yue\'s heart clenched. These were children! She didn\'t shout. She didn\'t raise the alarm. Instead, she slowly picked up her erhu and began to play.',
      'Through the night breeze, the erhu\'s voice drifted — sorrowful but not harsh, soft and flowing. The children froze. One by one they stopped, looking around to find the source of the music. Hua Yue stood in the moonlight on the rooftop and played the old folk song her grandmother had taught her — a melody about wandering and coming home.',
      'The children set down their pouches. A small girl began to cry. The oldest boy slowly raised both hands in surrender, voice trembling. "Please don\'t tell the adults. We... we were just so hungry."',
      'Hua Yue climbed down from the roof and sat among them. "Where are you from?" she asked gently. The boy hesitated, then told the truth: they were orphans from a neighboring town, made homeless by drought and brought to the city by well-meaning people — but the adult who was supposed to care for them had disappeared. They hadn\'t eaten in three days.',
      'Hua Yue stood up and made a decision. She knocked on the village chief\'s door. He appeared bleary-eyed. "Hua Yue? In the middle of the night —" "Chief," she said, "I found the thieves. But could you hear me out first?"',
      'The chief\'s expression shifted through several emotions as she spoke. He came outside and looked at the shivering, starving children. He sighed deeply. "I thought it was bandits..." Hua Yue said, "I have an idea. Tomorrow is the town fair. I\'ll go perform. I\'ll use whatever I earn to buy food for them — and then I\'ll help find them official shelter."',
      'The chief looked at this eight-year-old girl standing before him. He thought of the stories he\'d heard about Hua Mulan, and smiled. "All right. Go. I\'ll help you."',
      'At the fair the next day, Hua Yue\'s erhu drew larger and larger crowds. Applause, coin pouches, offerings from all sides. When the townspeople heard what had happened, they brought food and clothing of their own. Soon the orphans had warm meals, winter clothes, and government workers arrived to find them a real children\'s home.',
      'The oldest boy took her hand before he left. "We don\'t know your name." "I\'m Hua Yue," she said. He nodded. "Thank you, Sister Hua Yue. You don\'t look like a hero, but you did what a hero does." Hua Yue smiled. "I have a very great ancestor. She taught me — real courage only needs a kind heart. It doesn\'t always need a sword."',
    ],
  },

  {
    id: 'warcraft-peace',
    titleZh: '精灵与人类的盟约',
    titleEn: 'The Pact of Elves and Humans',
    descriptionZh: '在人类与精灵世代争战的大陆上，人类女孩凯拉和精灵男孩赛拉斯秘密成为朋友。当黑暗料理一场巨大的阴谋时，两个孩子必须说服两个种族共同战斗。',
    descriptionEn: 'In a land where humans and elves have warred for generations, a human girl and elf boy become secret friends — and must unite their peoples against a darkness that threatens everyone.',
    emoji: '🌿',
    category: 'fantasy',
    categoryZh: '奇幻冒险',
    categoryEn: 'Fantasy',
    gradient: 'from-emerald-500 via-green-500 to-teal-600',
    paragraphsZh: [
      '在艾泽拉斯大陆上，人类和精灵已经争战了两百年。人类住在南方的石头城堡里，精灵住在北方的古老森林里。两个种族互相不信任，孩子们从小就被告知："遇见另一个种族，要小心！"',
      '凯拉是人类将军的女儿，九岁。有一天，她偷偷跑进了禁止进入的边境森林，追一只逃跑的小松鼠——结果迷路了。森林里的树越来越高，光线越来越暗，凯拉开始害怕。',
      '就在这时，她听见了歌声。那是一首她从来没听过的语言唱成的歌，像流水，像鸟鸣，美丽极了。循着歌声走，她看见了一个和她年龄差不多的男孩，坐在树杈上，一边唱歌一边给一只受伤的小鸟包扎翅膀。男孩有长长的尖耳朵——那是精灵。',
      '凯拉想跑，但小鸟突然扑腾了一下，从男孩手上掉了下来！凯拉的手比腿快，本能地伸手，接住了小鸟。两个孩子面对面，凯拉手捧小鸟，两个人都愣住了。',
      '"你……救了它，"男孩用人类的语言说，发音有点奇怪，"谢谢你。我叫赛拉斯。""我叫凯拉，"她说，慢慢放松下来，"你会人类的语言？""我偷偷学的，"赛拉斯不好意思地说，"不许告诉任何人，我们精灵不允许学人类语言。"',
      '就这样，凯拉和赛拉斯成了秘密朋友。他们每周在森林边缘见一次面——凯拉带来人类的面包和书，赛拉斯带来精灵的草药和歌曲。他们交换语言，交换故事，慢慢地，他们发现了一件惊人的事：人类和精灵对彼此的了解，几乎全是错误的。',
      '精灵一直以为人类贪婪又粗鲁，但凯拉温柔而聪明。人类一直以为精灵骄傲又冷漠，但赛拉斯热情而善良。"我们怎么会这样误解对方这么久？"凯拉有一天问。"因为，"赛拉斯说，"我们的大人从来不和对方说话。"',
      '直到有一天，赛拉斯跑来见凯拉，脸色惨白，"出大事了。"他喘着气说，"森林深处发现了一支黑色军队，他们既不是人类也不是精灵——他们来自更远的地方，有一个名字叫做暗影军团。他们想趁我们两个种族争斗的时候，同时攻击我们两边！"',
      '"他们现在在哪里？"凯拉问。"分成两路，一路向人类的城堡去，一路向精灵的森林去，"赛拉斯说，"就在三天后的子夜。而且——他们已经在我们两边都安插了细作，如果我们分别向各自的大人报告，细作会说我们是对方派来的间谍……"',
      '"那我们怎么办？"赛拉斯问。凯拉想了想，"我们必须让你们的精灵王和我们的人类将军同时听到这个消息，而且必须是从我们两个的嘴里说出来，这样他们才会知道这不是谎言。"',
      '"可是……精灵王和人类将军两百年都没有说过话，"赛拉斯担心地说，"他们愿意见面吗？""也许不愿意，"凯拉说，"但是如果我们把两边的信也同时送到，让他们同时看到一模一样的信息……"',
      '两个孩子分头行动。凯拉闯进了父亲的营帐，把所有的事情一口气说了出来。父亲震怒——然后沉默——然后急忙召集军官。与此同时，赛拉斯跑回精灵树屋，同样把消息报给了精灵王。两边的反应出奇地相似：震惊，然后思考，然后向对方发出了三天来的第一封信。',
      '精灵王和人类将军在两百年来第一次见面——就在那片边境森林里。凯拉和赛拉斯站在两个大人中间，两边的军队保持距离，互相警惕。但当两位领袖打开彼此的信，发现里面的内容一字不差，都沉默了。',
      '"也许，"人类将军慢慢说，"我们需要重新谈谈。"三天后，两个种族并肩战斗，一起击退了暗影军团。战争结束的那个夜晚，凯拉和赛拉斯并肩坐在树杈上，看着两个种族的大人第一次举杯共饮。"我们做到了，"赛拉斯说。"我们做到了，"凯拉重复道。',
    ],
    paragraphsEn: [
      'On the continent of Azeroth, humans and elves had been at war for two hundred years. Humans lived in stone castles in the south; elves in ancient forests in the north. Neither trusted the other, and children were raised with one warning: "If you meet someone from the other race — be careful."',
      'Kayla was the daughter of a human general, nine years old. One day she slipped into the forbidden border forest chasing an escaped squirrel — and got completely lost. The trees grew taller, the light dimmer. Kayla was scared.',
      'Then she heard singing. A language she\'d never heard before, flowing like water, sweet as birdsong. She followed it to a boy about her age, perched on a tree branch, singing as he bandaged the wing of a tiny injured bird. The boy had long, pointed ears — he was an elf.',
      'Kayla tried to run — but the small bird suddenly fluttered and fell from the boy\'s hand! Her hands were faster than her feet; she reached out instinctively and caught it. The two children stared at each other over the bird.',
      '"You... saved it," the boy said in human language, with a slight accent. "Thank you. My name is Sylas." "I\'m Kayla," she said, slowly relaxing. "You speak human language?" "I taught myself in secret," Sylas said, embarrassed. "Don\'t tell anyone. Elves aren\'t allowed to learn it."',
      'And so, Kayla and Sylas became secret friends. Every week they met at the forest\'s edge — Kayla bringing human bread and books; Sylas bringing elven herbs and songs. They traded languages, traded stories. Slowly, they discovered something extraordinary: almost everything humans and elves believed about each other was wrong.',
      'Elves thought humans were greedy and crude — but Kayla was gentle and clever. Humans thought elves were proud and cold — but Sylas was warm and kind. "How did we misunderstand each other for so long?" Kayla asked one day. "Because," said Sylas, "our adults have never spoken to each other."',
      'Then one day Sylas came running, his face white. "Something terrible has happened." He gasped for breath. "Deep in the forest — a black army. Not human, not elf. They\'ve come from far away. They\'re called the Shadow Legion. They plan to attack both our peoples at once, while we\'re still fighting each other!"',
      '"Where are they now?" Kayla asked. "Split into two groups — one heading for the human castle, one for the elf forest," Sylas said. "In three days, at midnight. And they\'ve planted spies on both sides. If we each report to our own leaders separately, the spies will claim we\'re enemy agents..."',
      '"Then what do we do?" Sylas asked. Kayla thought. "We need both your Elf King and my father to hear this at the same time — from both of us together. Then they\'ll know it\'s not a lie."',
      '"But the Elf King and the human general haven\'t spoken in two hundred years," Sylas said anxiously. "Will they even agree to meet?" "Maybe not willingly," said Kayla. "But if we deliver identical messages to both sides at the same moment — so they see exactly the same information..."',
      'They split up. Kayla burst into her father\'s tent and laid out everything. He raged — then fell silent — then urgently called his officers. At the same time, Sylas ran to the elf tree-palace and reported to the Elf King. Both sides reacted the same way: shock, then thought, then each sent the other their first message in three days.',
      'The Elf King and the human general met for the first time in two hundred years — in the border forest. Kayla and Sylas stood between the two leaders while armies kept their distance, tense and watchful. But when the two leaders opened each other\'s letters and found the contents word-for-word identical, both went quiet.',
      '"Perhaps," the human general said slowly, "we need to talk again." Three days later the two races fought side by side and drove back the Shadow Legion. That night, Kayla and Sylas sat together on a tree branch, watching their people share a drink for the first time ever. "We did it," Sylas said. "We did it," Kayla echoed.',
    ],
  },
];
